echo "<--------[ Generating Variables on Following Schema ]-------->"
echo "MOD_PACK has following variables: "
echo "	name, a string"
echo "	It has the following associations: "
echo "		mods, has_and_belongs_to_many"
echo "		recipes, has_and_belongs_to_many"
echo "		items, has_and_belongs_to_many"
echo "		input_quantities, has_and_belongs_to_many"
echo "		output_quantities, has_and_belongs_to_many"
echo "		process_types, has_and_belongs_to_many"
echo "		item_classes, has_and_belongs_to_many"
echo "Generating MOD_PACK..."
rails g scaffold mod_pack name:string -f

echo "MOD has following variables: "
echo "	name, a string"     
echo "	It has the following associations:"
echo "		items, has_many"
echo "		mod_packs, has_and_belongs_to_many"
echo "Generating MOD..."
rails g scaffold mod name:string -f

echo "ITEM has following variables:"
echo "	name, a string"
echo "	basic_item, a boolean"
echo "	mods, a reference"
echo "	process_types, a reference"
echo "	item_classes, a reference"
echo "	It has the following associations:"
echo "		input_quantities, has_many, rich association"
echo "		output_quantities, has_many, rich association"
echo "		mods, belongs_to"
echo "		item_classes, has_and_belongs_to_many"
echo "		mod_packs, has_and_belongs_to_many"
echo "Generating ITEM..."
rails g scaffold item name:string basic_item:boolean mods:references -f

echo "RECIPE has following variables:"
echo "	preferred_recipe, a boolean"
echo "	process_types, a reference"
echo "	It has the following associations:"
echo "		input_quantities, has_many, rich association"
echo "		output_quantities, has_many, rich association"
echo "		mod_packs, has_and_belongs_to_many"
echo "		process_types, belongs_to"
echo "Generating RECIPE..."
rails g scaffold recipe preferred_recipe:boolean process_types:references -f

echo "INPUT_QUANTITY has following variables:"
echo "  count, an integer"
echo "	items, a reference"
echo "	recipes, a reference"
echo "	It has the following associations:"
echo "		items, belongs_to"
echo "		recipes, belongs_to"
echo "		mod_packs, has_and_belongs_to_many"
echo "Generating INPUT_QUANTITY..."
rails g scaffold input_quantity count:integer recipes:references items:references -f

echo "OUTPUT_QUANTITY has following variables:"
echo "  count, an integer"
echo "	items, a reference"
echo "	recipes, a reference"
echo "	It has the following associations:"
echo "		items, belongs_to"
echo "		recipes, belongs_to"
echo "		mod_packs, has_and_belongs_to_many"
echo "Generating OUTPUT_QUANTITY..."
rails g scaffold output_quantities count:integer recipes:references items:references -f

echo "PROCESS_TYPE has following variables"
echo "	name, a string"
echo "	description, text"
echo "	item_classes, a reference"
echo "	It has the following associations:"
echo "		recipe, has_many"
echo "		item_classes, has_and_belongs_to_many"
echo "		mod_packs, has_and_belongs_to_many"
echo "Generating PROCESS_TYPE..."
rails g scaffold process_type name:string description:text -f

echo "ITEM_CLASS has following variables"
echo "	name:string"
echo "	It has the following associations:"
echo "		items, has_and_belongs_to_many"
echo "		process_types, has_and_belongs_to_many"
echo "		mod_packs, has_and_belongs_to_many"
echo "Generating ITEM_CLASS..."
rails g scaffold item_class name:string -f